development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sample_development
  pool: 5
  username: root
  password: 
  host: yu-no-vagrant

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sample_test
  pool: 5
  username: root
  password: 
  host: yu-no-vagrant

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sample_production
  pool: 5
  username: root
  password: 
  host: yu-no-vagrant